source 'https://github.com/CocoaPods/Specs.git'


pod_dependencies = Proc.new {
  pod 'VinylRecord' #, :path => "../iActiveRecord/VinylRecord.podspec"
  pod 'JSONKit-NoWarning', '~> 1.2'
}


target 'NLDelayedJob', :exclusive => true do
  pod "NLDelayedJob", :path => "../"
  pod_dependencies.call
end

target 'Tests', :exclusive => true do
  pod "NLDelayedJob", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod_dependencies.call
end
